### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by PuercoPop**
:wave: Thanks for taking the time to writing the library, although in general when working only with list a `plist` would be a better format as not only it allows for richer data types and that can be READ directly by the CL Reader, when working with Heroku or other platforms and languages using .env files would be the better choice. Below I list the changes I'm proposing

# Improve the READing of env files

• Ignore comments, the previous code would interpret "# foo=var " as
  a valid entry and attempt to assign in.

• Accept entries in the form of "VAR_NAME=" with the value being taken
  as an empty string "".

• Ignore blank lines or lines consisting only of whitespace.

## Decouple the READing from the LOADing of env files.

The main purpose of this is to be able to provide restarts on a case per
case basis. In particular to detect repeated entries.

## Provide Restarts for common cases.

• Skip malformed entries.
• Chose which value to use in the case of a repeated entry.

Can you think of any other case it would be useful to handle?

## Remove LOAD-ENV and GET-ENV

As they are already provided by UIOP.

## Don't use UIOP:READ-FILE-LINES

• UIOP:READ-FILE-LINES loads all of the file in memory at once, we can
  avoid that by using a common LOOP idiom

```lisp
  (with-open-file (in <path>)
    (loop :for line := (read-line in nil)
          :while line
          :do ...))
```

The second argument tells READ-LINE to return NIL when the EOF is
reached.

# Dependencies

## Alexandria

Alexandria is _the_ utility library of CL, to the point that it is
almost considered part of the base language, along with
split-sequence. I'm only using case I'm using IF-LET, the better
alternative to anaphoric macros.

## Serapeum

Arguably I shouldn't pull in this dependency as LRET could be replaced
by:

```lisp
  (let ((env (make-hash-table :test 'equalp)))
    ...
    env)
```

But I wanted an excuse to show you the library given that you are new to
CL.

# Add test case: bad.env

• Test case for empty lines.
• Test case for comments.
• Test case with lines consisting only of whitespace.

# Style changes

• Use keywords for LOOP clases.

## ASDF System definition

• ASDF allows 'subsystems' to be defined using a '/' and have them live
  in the same file as the main system. This way we avoid two different
  ASD files.

• Instead of grouping all the files in a top-level module component use
  the pathname option of the system definition.

• System names are strings. Although it is permitted to a string
  designator, use strings to list when referencing them in the
  depends-on clause.

## Documentation

• The CONTRIBUTING documentation listed cmake as a dependency but only
  Make is required. Updating the link to point to GNU Make.

## Update package nickname

In CL one can use most characters are part of the variable name and I
think ".env" is cooler than "dotenv".

# Ideas for additional features

• WRITE-ENV: Write the environment to the file. Could be useful to store
  the ENV restarts where involed.

• WITH-ENV: Similar to other WITH-FOO[0] macros, we could modify the
  envariables and restore their previous values or unset (man 3
  unsetsenv) them to leave the process in the same state as we found it
  after evaluating some code. But I can't really think of situations of
  where it would be useful. Maybe to start sub-processes with a
  particular environment?

I haven't updated the tests though :shame:

[0]: http://random-state.net/log/3390120648.html

Associated Issue: #<issue number>

Please get familiar with the contributing guide before submitting a PR:     
https://github.com/ollelauribostrom/cl-dotenv/blob/master/.github/CONTRIBUTING.md

Let me know which ones you like so I can send a PR per feature

### CODE REVIEW

**Comment by ollelauribostrom** [comment]
Awesome work with this PR, thanks! 👍

- I really like that we are now ignoring comments, accepting entries in the form of `VAR_NAME=` and ignoring blank lines ✅
- The restarts are great (can't think of any additional scenarios right now but we can extend that later on). ✅
- I have nothing against the new dependencies or the removal of `LOAD-ENV` and `GET-ENV` ✅
- Thanks for spotting the dependency mistake in `CONTRIBUTING.md` ✅

## Thoughts before merging
- I think that we actually need two different ASDF System definition files to be able to run `run-prove` in the Makefile. (This means revert the `Makefile`, bring back the `cl-dotenv-test.asd` and update the system names)
- The tests are currently failing (We can start of with some basic scenarios but would be cool to get them passing before merging this)
- Move `tests/bad.env` -> `tests/.env-corrupt` and use that one in the tests
- I like the ".env" nickname, but maybe we can use them both?
- Exclude the `LICENSE` from the commit (Contains no changes)
- Any finally (not sure about this one): Isn't there a undeclared dependency to `uiop`?

**Comment by PuercoPop** [comment]
> I think that we actually need two different ASDF System definition files to be able to run run-prove in the Makefile. (This means revert the Makefile, bring back the cl-dotenv-test.asd and update the system names)

I don't use Roswell so I can't really test how run-prove works. But to run the tests from the Makefile the following should do. Although currently there is a typo in test system's name in the test-op that I would have to fix first for the snippet to work

```
test:
	sbcl --eval "(asdf:test-system \"cl-dotenv\")"
```

 I'll revert the changes to the Makefile to keep the Roswell functionality working

> The tests are currently failing (We can start of with some basic scenarios but would be cool to get them passing before merging this)

We'll fix the tests so we can move forward.

> Move tests/bad.env -> tests/.env-corrupt and use that one in the tests
> I like the ".env" nickname, but maybe we can use them both?

Will do

> Exclude the LICENSE from the commit (Contains no changes)

The change was to remove the executable permissions from the file. I could split it into a separate PR if you prefer.

> Any finally (not sure about this one): Isn't there a undeclared dependency to uiop?

Yeah, that is important for inclusion in Quicklisp. Will add the dependency.

**Comment by PuercoPop** [comment]
Updated the tests and reverted the changes to the Makefile and the system definition names and files. They pass on my machine but seem travis seems unable to to run them. Could you check if I missed something?

**Comment by ollelauribostrom** [comment]
Thanks!

The Travis build only fails for the clisp target. Does the build log tell you anything? https://travis-ci.org/ollelauribostrom/cl-dotenv/jobs/427511775

**Comment by PuercoPop** [comment]
The most recent CLISP I was able to build (which is the one I have on my machine) is `GNU CLISP 2.49.60+ (2017-06-25)`. Which in turns ships which a really old asdf version, 2.26. It seems that a dependency of `serapeum`, `trivial-file-size` requires ASDF3+ which is why the CLISP build fails (at least on my machine). Personally I would drop testing on CLISP until they release a version with ASDF3.

**Comment by ollelauribostrom** [comment]
Removed the CLISP target and merged this. Thanks a lot for the awesome job!

**Pull request merged**
